"""Real Playwright e2e coverage for SDLCAIP1-35's homepage article list page
styling (design-tokens application).

Not to be confused with `test_articles_list_styling_e2e.py` (SDLCAIP1-32),
which tests the `frontend/` React admin article table page -- a completely
different page and tech stack. This suite covers the front-end public
static homepage list page (`index.html` / `page/{n}.html`), generated by
`_render_list_page_html` (src/cms_aipilot/main.py), same as
`test_articles_list_e2e.py`.

`_render_list_page_html` is a pure string-building function with no S3/
DynamoDB dependency, so it's called directly to obtain the HTML string
(unlike `test_article_detail_page_e2e.py`, which has to go through
`_generate_and_upload_static_page` with S3 mocked because that's the only
entry point available for that page).

This story's `<head>` now references an external stylesheet
(`<link rel="stylesheet" href="/design-tokens.css">`), which
`page.set_content()` cannot exercise: a page loaded via `set_content` sits
at the `about:blank` origin, which has no base to resolve the absolute
`/design-tokens.css` URL against, so the browser never issues (and
Playwright can never intercept) that stylesheet request -- the computed
styles asserted below would silently fall back to browser defaults instead
of reflecting the design tokens. Instead we intercept a fixed fake origin
with `page.route(...)` and `page.goto(...)` to it, routing `/index.html` to
the rendered list-page HTML and `/design-tokens.css` to the real token file
content (read from `cms_aipilot.main._DESIGN_TOKENS_PATH`, the same file
`_generate_and_upload_design_tokens()` uploads -- not a hand-copied literal,
so this test can't silently drift out of sync with the real file), aborting
everything else. No real network or S3 access occurs.
"""

from __future__ import annotations

from playwright.sync_api import Page, Route

from cms_aipilot.main import _DESIGN_TOKENS_PATH, _render_list_page_html

BASE_URL = "https://sdlcaip1-35.e2e.test"
INDEX_URL = f"{BASE_URL}/index.html"

ARTICLE_ITEMS = [
    {
        "id": "a1",
        "title": "Styled List Item Title",
        "content": "ignored",
        "published_at": "2026-08-10T09:00:00",
    }
]


def _load_list_page(page: Page) -> None:
    html = _render_list_page_html(ARTICLE_ITEMS, page=1, total_pages=1)
    with open(_DESIGN_TOKENS_PATH, encoding="utf-8") as f:
        tokens_css = f.read()

    def handler(route: Route) -> None:
        url = route.request.url
        if url == INDEX_URL:
            route.fulfill(status=200, content_type="text/html", body=html)
        elif url == f"{BASE_URL}/design-tokens.css":
            route.fulfill(status=200, content_type="text/css", body=tokens_css)
        else:
            route.abort()

    page.route(f"{BASE_URL}/**", handler)
    page.goto(INDEX_URL)


class TestArticleListPageColorAndFontUseDesignTokens:
    """AC1: colors/fonts switch to var(--color-*)/var(--font-family-base)."""

    def test_link_color_uses_text_primary_token(self, page: Page) -> None:
        _load_list_page(page)

        link = page.locator(".article-list__link")
        color = link.evaluate("el => getComputedStyle(el).color")

        # --color-text-primary: #111111 -> rgb(17, 17, 17)
        assert color == "rgb(17, 17, 17)"

    def test_list_uses_font_family_base_token(self, page: Page) -> None:
        _load_list_page(page)

        article_list = page.locator(".article-list")
        font_family = article_list.evaluate("el => getComputedStyle(el).fontFamily")

        assert "PingFang TC" in font_family


class TestArticleListItemHasNoBorderShadowOrBackground:
    """AC2: list items don't use border/box-shadow/background-color for
    separation."""

    def test_item_has_no_border_shadow_or_background(self, page: Page) -> None:
        _load_list_page(page)

        item = page.locator(".article-list__item")
        border_bottom_width = item.evaluate("el => getComputedStyle(el).borderBottomWidth")
        box_shadow = item.evaluate("el => getComputedStyle(el).boxShadow")
        background_color = item.evaluate("el => getComputedStyle(el).backgroundColor")

        assert border_bottom_width == "0px"
        assert box_shadow == "none"
        assert background_color == "rgba(0, 0, 0, 0)"


class TestArticleListTitleAndDateAreCentered:
    """AC3: title and date are centered."""

    def test_link_and_meta_text_align_center(self, page: Page) -> None:
        _load_list_page(page)

        link = page.locator(".article-list__link")
        meta = page.locator(".article-list__meta")

        assert link.evaluate("el => getComputedStyle(el).textAlign") == "center"
        assert meta.evaluate("el => getComputedStyle(el).textAlign") == "center"
