"""Real Playwright e2e coverage for SDLCAIP1-28's front-end search page
(search.html).

Like SDLCAIP1-20's static article detail page (test_article_detail_page_e2e.py),
this story's output is not part of `frontend/` -- it's a plain static HTML/JS
file generated by `_generate_and_upload_search_page` (src/cms_aipilot/main.py)
and uploaded to S3, served directly to site visitors. There is no build/dev
server to stand up for it, so this suite generates the exact HTML string the
function would upload (S3 mocked, same as tests/test_search_page.py) and
loads it into a real browser via `page.set_content`.

Unlike the article detail page, this page's script does a client-side
`fetch("/search/index.json")`. A page loaded via `page.set_content` has
`about:blank` as its origin, so a bare relative fetch fails outright. We
intercept it with `page.route("**/search/index.json", ...)` (same
interception pattern as test_articles_list_e2e.py's `page.route`/
`route.fulfill`), which Playwright honours even for pages whose document was
loaded via `set_content` rather than `goto` navigation, verified empirically
by running this suite.
"""

from __future__ import annotations

import json
from unittest.mock import MagicMock, patch

from playwright.sync_api import Page, Route

from cms_aipilot.main import _generate_and_upload_search_page

SEARCH_INDEX = [
    {
        "id": "a1",
        "title": "Sunrise over the mountains",
        "content": "A quiet plain-text article body about hiking trails.",
        "published_at": "2026-01-01T00:00:00",
    },
    {
        "id": "a2",
        "title": "Unrelated headline",
        "content": "This body mentions a Keyword somewhere in the middle of it.",
        "published_at": "2026-01-02T00:00:00",
    },
]


def _generated_html(monkeypatch) -> str:
    monkeypatch.setenv("ARTICLES_STATIC_BUCKET_NAME", "test-articles-static-bucket")
    fake_s3 = MagicMock()
    with patch("cms_aipilot.main.get_s3_client", return_value=fake_s3):
        _generate_and_upload_search_page()
    return fake_s3.put_object.call_args.kwargs["Body"]


SEARCH_PAGE_URL = "https://e2e-search-page.example/search.html"


def _load_with_index(page: Page, monkeypatch, index_data: list[dict]) -> list[str]:
    """Loads the generated search.html into the browser with
    /search/index.json intercepted to return `index_data`. Returns the list
    of request URLs observed during the page's lifetime (for AC8).

    `page.set_content` puts the document at the `about:blank` origin, where a
    relative `fetch("/search/index.json")` throws immediately (invalid URL to
    resolve against) rather than issuing a network request Playwright can
    intercept -- confirmed empirically running this suite (0 requests seen,
    matches silently empty via the script's `.catch(() => indexData = [])`
    fallback). A real page origin is required for the relative fetch to
    become an interceptable request, so instead we intercept the page's own
    HTML document at a fake https URL (mirroring how `/search.html` is
    actually served from the S3 static site's root) and navigate to it, in
    addition to intercepting `/search/index.json`.
    """
    requested_urls: list[str] = []
    page.on("request", lambda req: requested_urls.append(req.url))

    html = _generated_html(monkeypatch)

    def handle_page(route: Route) -> None:
        route.fulfill(status=200, content_type="text/html", body=html)

    def handle_index(route: Route) -> None:
        route.fulfill(
            status=200,
            content_type="application/json",
            body=json.dumps(index_data),
        )

    page.route(SEARCH_PAGE_URL, handle_page)
    page.route("**/search/index.json", handle_index)

    page.goto(SEARCH_PAGE_URL)
    # Let the fetch().then() microtask chain resolve before interacting.
    page.wait_for_timeout(100)
    return requested_urls


class TestSearchPageLinkedFromOtherStaticPages:
    """AC1: independent search page reachable from index/article pages."""

    def test_article_detail_page_has_link_to_search_page(self, page: Page, monkeypatch) -> None:
        from cms_aipilot.main import Article, _generate_and_upload_static_page

        monkeypatch.setenv("ARTICLES_STATIC_BUCKET_NAME", "test-articles-static-bucket")
        fake_s3 = MagicMock()
        with patch("cms_aipilot.main.get_s3_client", return_value=fake_s3):
            _generate_and_upload_static_page(
                Article(id="a1", title="T", content="C", published_at="2026-01-01T00:00:00")
            )
        html = fake_s3.put_object.call_args.kwargs["Body"]
        page.set_content(html)

        link = page.get_by_role("link", name="搜尋文章")
        assert link.is_visible()
        assert link.get_attribute("href") == "/search.html"

    def test_list_page_has_link_to_search_page(self, page: Page) -> None:
        from cms_aipilot.main import _render_list_page_html

        html = _render_list_page_html(page_items=[], page=1, total_pages=1)
        page.set_content(html)

        link = page.get_by_role("link", name="搜尋文章")
        assert link.is_visible()
        assert link.get_attribute("href") == "/search.html"


class TestSearchByTitleKeyword:
    """AC2: keyword matching only the title surfaces that article."""

    def test_title_only_keyword_shows_matching_article(self, page: Page, monkeypatch) -> None:
        _load_with_index(page, monkeypatch, SEARCH_INDEX)

        page.fill("#search-input", "Sunrise")

        result_link = page.locator("#search-results a")
        assert result_link.count() == 1
        assert result_link.text_content() == "Sunrise over the mountains"
        assert result_link.get_attribute("href") == "/articles/a1.html"


class TestSearchByFullTextKeyword:
    """AC3: keyword appearing only in the body (not the title) still matches."""

    def test_body_only_keyword_shows_matching_article(self, page: Page, monkeypatch) -> None:
        _load_with_index(page, monkeypatch, SEARCH_INDEX)

        page.fill("#search-input", "hiking trails")

        result_link = page.locator("#search-results a")
        assert result_link.count() == 1
        assert result_link.text_content() == "Sunrise over the mountains"


class TestSearchCaseInsensitiveSubstring:
    """AC4: matching is case-insensitive substring matching."""

    def test_lowercase_query_matches_mixed_case_source_text(
        self, page: Page, monkeypatch
    ) -> None:
        _load_with_index(page, monkeypatch, SEARCH_INDEX)

        page.fill("#search-input", "keyword")

        result_link = page.locator("#search-results a")
        assert result_link.count() == 1
        assert result_link.text_content() == "Unrelated headline"


class TestSearchNoResults:
    """AC5: no matches shows an explicit empty-result message, no items."""

    def test_unmatched_keyword_shows_empty_message_and_no_items(
        self, page: Page, monkeypatch
    ) -> None:
        _load_with_index(page, monkeypatch, SEARCH_INDEX)

        page.fill("#search-input", "nonexistent-keyword-xyz")

        assert page.locator("#search-results li").count() == 0
        empty_message = page.locator("#search-empty")
        assert empty_message.is_visible()
        assert "查無" in empty_message.text_content()


class TestSearchResultsNotPaginated:
    """AC6: more than 10 matches still render all on one page, no pagination."""

    def test_more_than_ten_matches_all_render_without_pagination_controls(
        self, page: Page, monkeypatch
    ) -> None:
        many_items = [
            {
                "id": f"a{i}",
                "title": f"Common headline number {i}",
                "content": "filler",
                "published_at": "2026-01-01T00:00:00",
            }
            for i in range(15)
        ]
        _load_with_index(page, monkeypatch, many_items)

        page.fill("#search-input", "Common headline")

        assert page.locator("#search-results li").count() == 15
        # No pagination control / "load more" affordance anywhere on the page.
        assert page.get_by_text("下一頁").count() == 0
        assert page.get_by_text("顯示更多").count() == 0
        assert page.locator("[class*='pagination']").count() == 0


class TestSearchEmptyInputShowsNothing:
    """AC7: on load, before any input, no results and no empty-state message."""

    def test_freshly_loaded_page_shows_no_results_and_no_empty_message(
        self, page: Page, monkeypatch
    ) -> None:
        _load_with_index(page, monkeypatch, SEARCH_INDEX)

        assert page.locator("#search-results li").count() == 0
        assert not page.locator("#search-empty").is_visible()

    def test_clearing_input_after_a_search_also_shows_no_empty_message(
        self, page: Page, monkeypatch
    ) -> None:
        """Guards the same AC7 behaviour is preserved when the user backs out
        a query entirely rather than just never having typed anything."""
        _load_with_index(page, monkeypatch, SEARCH_INDEX)

        page.fill("#search-input", "nonexistent-keyword-xyz")
        assert page.locator("#search-empty").is_visible()

        page.fill("#search-input", "")

        assert page.locator("#search-results li").count() == 0
        assert not page.locator("#search-empty").is_visible()


class TestSearchIsClientSideOnly:
    """AC8: matching happens purely client-side; no backend /articles* calls."""

    def test_searching_never_requests_backend_articles_api(
        self, page: Page, monkeypatch
    ) -> None:
        requested_urls = _load_with_index(page, monkeypatch, SEARCH_INDEX)

        for query in ["Sunrise", "keyword", "hiking", "nonexistent-keyword-xyz", ""]:
            page.fill("#search-input", query)

        assert not any("/articles" in url for url in requested_urls)
        # The only network fetch made is the pre-downloaded search index.
        assert any("/search/index.json" in url for url in requested_urls)
